### ISSUE TITLE
Get list of modified files from TFVC Provider

### ISSUE THREAD

**Issue by dtretyakov** [rugpanov/TeamCity-extension-for-VSCode#3]
We need to have a list of modified files to trigger a personal build.

**Comment by rugpanov** [comment]
Currently there is only private api to get it. We should resolve how the extension should get access to this api.

**Comment by rugpanov** [comment]
In the archive there is a patch for tfvc extension. The patch extends extension api to export list of absolute paths of changed files. (The list is required for triggering a personal build via TeamCity extension.) [API-for-TC-extension.zip](https://github.com/rugpanov/TeamCity-extension-for-VSCode/files/1133730/0001-API-for-TC-extension.zip).

We should decide what else information does TeamCity extension require, and sent a request to tfvc extension developers.

**Comment by rugpanov** [comment]
Implemented at 62d153feb492554ca6604b34c02434e725c0b861
