### ISSUE TITLE
Get repository info from TFVC Provider

### ISSUE THREAD

**Issue by dtretyakov** [rugpanov/TeamCity-extension-for-VSCode#5]
We need to have repository information to find a suitable build configuration.

**Comment by rugpanov** [comment]
tfvcProvider._model.IncludedGroup.resources[i].PendingChange.localItem contains a local location of changed files; 
tfvcProvider._model.IncludedGroup.resources[i].PendingChange.serverItem contains a server URL of changed resource

**Comment by rugpanov** [comment]
Implemented at 62d153feb492554ca6604b34c02434e725c0b861
