### ISSUE TITLE
Queue personal build with modified files

### ISSUE THREAD

**Issue by dtretyakov** [rugpanov/TeamCity-extension-for-VSCode#9]
We should be able to trigger personal builds in TeamCity for specified build configurations by sending request with a list of modified files.

**Comment by dtretyakov** [comment]
We need to format a patch with modified files before triggering build. To see how it works we could take a look at the [Command Line Remote Run Tool](https://confluence.jetbrains.com/display/TW/Command+Line+Remote+Run+Tool). [The repository](http://svn.jetbrains.org/teamcity/plugins/) of this tool.

**Comment by rugpanov** [comment]
Implemented with a command.line util at 406b42b91019d9aa35fea7afe061b714b5cc6663 and b565884ba3f1edcedca49e9b5eff456240e63d2d
